name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        php-versions:
          - '7.4'
          - '8.0'
          - '8.4'
        
        include:
          - php-version: '8.5'
            experimental: true
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup PHP Version ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: cs2pr, phpcs

    - name: Check syntax error in sources
      run: find . -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

    - name: Clear cache of Composer
      run: composer clear-cache

    - name: Validate Composer.json and composer.lock
      run: composer update

    - name: Install dependencies
      run: composer install -q -n -a --no-progress --prefer-dist

    - name: Check Code Styles
      continue-on-error: true
      run: ./vendor/bin/phpcs

    - name: Run PHPCBF
      if: ${{ matrix.php-versions == '8.4' }}
      run: ./vendor/bin/phpcbf
      continue-on-error: true
        
    - name: Commit PHPCBF Changes
      if: ${{ matrix.php-versions == '8.4' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      
